//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task_wpf_v2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public Nullable<int> userr_id { get; set; }
        public int task_id { get; set; }
        public string task_title { get; set; }
        public string task_desc { get; set; }
        public string task_state { get; set; }
        public Nullable<System.DateTime> duedate { get; set; }
    
        public virtual user user { get; set; }
    }
}
